#!/bin/bash
# shellcheck disable=SC2154

echo -e "-------------------------------------------------------------------------"
echo -e "Configuring KDE Plasma"

echo -e "-------------------------------------------------------------------------"
echo -e "Installing archer-backup and restoring home"

mv /Archer-main/quiver/scripts/archer-backup /usr/local/bin/archer-backup
chmod a+x /usr/local/bin/archer-backup

sudo -u "$user" /usr/local/bin/archer-backup --restore /Archer-main/quiver/configs/Archer.tar.gz

echo -e "-------------------------------------------------------------------------"
echo -e "Setting up Breeze GTK theme"

mkdir -p /home/"$user"/.config/autostart/
chown "$user":"$user" /home/"$user"/.config/autostart/
chmod 755 /home/"$user"/.config/autostart/

cat <<-END > /home/"$user"/.config/autostart/breeze-gtk.desktop
[Desktop Entry]
Type=Application
Name=Set Breeze GTK theme
Exec=sh -c 'sleep 2; qdbus6 org.kde.GtkConfig /GtkConfig org.kde.GtkConfig.setGtkTheme Breeze; rm -f ~/.config/autostart/breeze-gtk.desktop'
NoDisplay=true
END
chown "$user":"$user" /home/"$user"/.config/autostart/breeze-gtk.desktop
