#!/bin/bash
# Main script 2/3
# shellcheck disable=SC2002,SC2164,SC2269,SC1090,SC1091

# Declaring exported variables from first script
hostname=${hostname}
user=${user}
root_password=${root_password}
user_password=${user_password}
install_type=${install_type}
kernel=${kernel}
keyboard_keymap=${keyboard_keymap}
default_locale=${default_locale}
timezone=${timezone}
root_partition=${root_partition}
disk_encryption=${disk_encryption}
encrypted_root_partition=${encrypted_root_partition}

source /bash-tui-toolkit.sh
rm /bash-tui-toolkit.sh

setup_pacman() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling multilib repository"

	sed -i '/^#\[multilib\]/s/^#//' /etc/pacman.conf
	sed -i '/^\[multilib\]$/,/^#Include/ s/^#//' /etc/pacman.conf

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling parallel downloads"

	sed -i '/^#ParallelDownloads/s/^#//' /etc/pacman.conf

	echo -e "-------------------------------------------------------------------------"
	echo -e "Creating pacman hook directory"

	sed -i '/^#HookDir/s/^#//' /etc/pacman.conf
	mkdir -p /etc/pacman.d/hooks/

	echo -e "-------------------------------------------------------------------------"
	echo -e "Adding candy and color to pacman"

	sed -i '/^ParallelDownloads = .*/a ILoveCandy' /etc/pacman.conf
	sed -i '/^#Color/s/^#//' /etc/pacman.conf

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling Chaotic-AUR repo"

	pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
	pacman-key --lsign-key 3056513887B78AEB
	pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

	echo "[chaotic-aur]" >> /etc/pacman.conf
	echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf


	echo -e "-------------------------------------------------------------------------"
	echo -e "Updating pacman databases"

	pacman -Syu --noconfirm
}

setup_system() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting timezone to $timezone"

	timedatectl set-timezone "$timezone"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Creating NetworkManager script to get timezone automatically"

    mkdir -p /etc/NetworkManager/dispatcher.d/

	cat <<-END >/etc/NetworkManager/dispatcher.d/09-timezone
#!/bin/sh
case "\$2" in
    up)
        timedatectl set-timezone "\$(curl --fail https://ipapi.co/timezone)"
    ;;
esac
END

chmod +x /etc/NetworkManager/dispatcher.d/09-timezone

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting hardware clock"

	hwclock --systohc

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling network time syncronization"

	systemctl enable systemd-timesyncd.service
	timedatectl set-ntp true

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting $default_locale as locale and $keyboard_keymap as keymap"

	locale-gen

	echo "LANG=$default_locale" >>/etc/locale.conf
	echo "KEYMAP=$keyboard_keymap" >>/etc/vconsole.conf

    localectl set-locale "$default_locale"
    localectl set-keymap "$keyboard_keymap"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting hostname to $hostname"

	echo "$hostname" >>/etc/hostname

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling btrfs module in mkinitcpio.conf"

	sed -i 's/^MODULES=()/MODULES=(btrfs)/' /etc/mkinitcpio.conf

	if [[ $disk_encryption == "yes" ]]; then
		echo -e "-------------------------------------------------------------------------"
		echo -e "Enabling encryption hook in mkinitcpio.conf"

		sed -i '/^HOOKS=/ s/\(filesystems\)/sd-encrypt \1/' /etc/mkinitcpio.conf
	fi

	echo -e "-------------------------------------------------------------------------"
	echo -e "Rebuilding the initramfs image"

	mkinitcpio -P

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting up sudo permissions for wheel group"

	sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

	echo -e "-------------------------------------------------------------------------"
	echo -e "Temporarily removing password requirement for wheel group"

	sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers

	echo -e "-------------------------------------------------------------------------"
	echo -e "Creating user $user"

	groupadd -f git
	useradd -m -G sys,wheel,rfkill,git -s /bin/bash "$user"

	echo "-------------------------------------------------------------------------"
	echo "Setting root password"
	echo "root:$root_password" | chpasswd

	echo "-------------------------------------------------------------------------"
	echo "Setting user password"
	echo "$user:$user_password" | chpasswd

	unset root_password user_password

	echo -e "-------------------------------------------------------------------------"
	echo -e "Adding ~/.local/bin PATH to /etc/profile.d/custom-path.sh"

	echo "export PATH=\$PATH:\$HOME/.local/bin" >>/etc/profile.d/custom-path.sh
}

setup_paru_pipx() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing Paru AUR helper"

	if ! package_installer "git paru-git" pacman; then

		package_installer "git rust cmake" pacman

		cd /home/"$user"/
		sudo -u "$user" git clone https://aur.archlinux.org/paru-git.git 2>&1 | sudo_quiet
		cd paru

		while true; do
			sudo -u "$user" makepkg -si --needed --noconfirm 2>&1 | sudo_quiet && break
			echo "$(tput setaf 9)Paru build failed. Retrying...$(tput sgr0)"
		done
		cd .. && rm -rf paru/ && cd /
	fi

	paru -Syu

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing Python pipx"

	package_installer "python-pipx"
}

setup_grub() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing Grub packages"

	package_installer "grub-btrfs efibootmgr inotify-tools"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Creating efibootmgr wrapper script to prevent fail"

	cat <<-END >/usr/local/bin/efibootmgr
#!/bin/sh
exec /usr/bin/efibootmgr -e 3 "\$@"
	END
	chmod +x /usr/local/bin/efibootmgr

	echo -e "-------------------------------------------------------------------------"
	echo -e "Configuring Grub"

	grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --recheck
	grub-mkconfig -o /boot/grub/grub.cfg

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing Grub theme"

	mv /Archer-main/quiver/bootloader/themes/arch-silence /boot/grub/themes/arch-silence
	sed -i '/^[#]*GRUB_THEME=/c\GRUB_THEME="\/boot\/grub\/themes\/arch-silence\/theme.txt"' /etc/default/grub

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling GRUB-btrfsd snapshot daemon"

	systemctl enable grub-btrfsd

	echo -e "-------------------------------------------------------------------------"
	echo -e "Disabling snapshot listing in pacman for grub-btrfs"

	sed -i '/^[#]*GRUB_BTRFS_SHOW_SNAPSHOTS_FOUND=/s/true/false/' /etc/default/grub-btrfs/config
	sed -i '/^#GRUB_BTRFS_SHOW_SNAPSHOTS_FOUND/s/^#//' /etc/default/grub-btrfs/config

	echo -e "-------------------------------------------------------------------------"
	echo -e "Removing 'quiet' kernel parameter"

	sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/s/ quiet//g' /etc/default/grub

	if [[ $disk_encryption == "yes" ]]; then
		echo -e "-------------------------------------------------------------------------"
		echo -e "Setting encryption kernel parameters"

		root_disk_uuid=$(blkid -s UUID -o value "$encrypted_root_partition")
		sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 rd.luks.name=$root_disk_uuid=root root=\/dev\/mapper\/root\"/" /etc/default/grub
	fi

		echo -e "-------------------------------------------------------------------------"
		echo -e "Setting up netboot.xyz"

        # https://netboot.xyz/docs/kb/hardware/usb-keyboard
		curl -L https://boot.netboot.xyz/ipxe/netboot.xyz-legacy.efi -o /boot/EFI/netboot.xyz-legacy.efi
		curl -L https://boot.netboot.xyz/ipxe/netboot.xyz.efi -o /boot/EFI/netboot.xyz.efi

		cat /Archer/quiver/configs/45_netboot.xyz >/etc/grub.d/45_netboot.xyz
		chown root:root /etc/grub.d/45_netboot.xyz
}

setup_cpu() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Checking CPU"

	lscpu_output=$(lscpu)
	read -r -t 1

	if [[ $lscpu_output == *"AuthenticAMD"* ]]; then
		echo -e "Found AMD"
		amd_cpu

	elif [[ $lscpu_output == *"GenuineIntel"* ]]; then
		echo -e "Found Intel"
		intel_cpu
	fi

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting cpu kernel parameters"

	[ -n "$cpu_kernel_parameters" ] && sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 $cpu_kernel_parameters\"/" /etc/default/grub
}

amd_cpu() {
	cpu_kernel_parameters="nowatchdog modprobe.blacklist=sp5100_tco"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing packages"

	package_installer "amd-ucode"
}

intel_cpu() {
	cpu_kernel_parameters="intel_iommu=on iommu=pt nowatchdog modprobe.blacklist=iTCO_wdt"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing packages"

	package_installer "intel-ucode thermald"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling thermald service"

	systemctl enable thermald.service
}

setup_gpu() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Checking GPU"

	lspci_output=$(lspci | grep VGA)
	lspci_output_full=$(lspci)
	read -r -t 1

	if [[ $lspci_output == *"Radeon"* ]] || [[ $lspci_output == *"AMD"* ]]; then
		echo -e "Found AMD"
		amd_gpu

	elif [[ $lspci_output == *"Integrated Graphics Controller"* ]] || [[ $lspci_output == *"Intel Corporation HD"* ]] || [[ $lspci_output == *"Intel Corporation UHD"* ]]; then
		echo -e "Found Intel"
		intel_gpu

	elif [[ $lspci_output == *"NVIDIA"* ]] || [[ $lspci_output == *"GeForce"* ]]; then
		echo -e "Found NVIDIA"
		nvidia_gpu

	elif [[ ${lspci_output} =~ (Virtio|QEMU) ]] || [[ ${lspci_output_full} =~ (Virtio|QEMU) ]]; then
		echo "Found QEMU"
		qemu_gpu
	fi

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting gpu kernel parameters"

	[ -n "$gpu_kernel_parameters" ] && sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 $gpu_kernel_parameters\"/" /etc/default/grub
}

amd_gpu() {
	gpu_kernel_parameters=""

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing packages"

	package_installer "mesa vulkan-radeon xf86-video-amdgpu"
}

nvidia_gpu() {
	gpu_kernel_parameters="nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nvidia.NVreg_PreserveVideoMemoryAllocations=1"

	if [[ $lspci_output == *"RTX"* ]]; then
		nvidia_driver="nvidia-open-dkms nvidia-utils"

	elif [[ $lspci_output == *"GTX"* ]]; then
		echo -e "Found GTX card. Installing nvidia-580xx-dkms"
		nvidia_driver="nvidia-580xx-dkms nvidia-580xx-settings nvidia-580xx-utils"

	else
		echo -e "Installing Nouveau driver"
		nvidia_driver="mesa"
	fi

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing packages"

	package_installer "$nvidia_driver"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling support for suspend/wakeup"

	systemctl enable nvidia-suspend.service
	systemctl enable nvidia-hibernate.service
	systemctl enable nvidia-resume.service
}

intel_gpu() {
	gpu_kernel_parameters=""

	# Need a way to test for new and old gpu and also if cpu
	# QuickSync # LEGACY intel-media-driver intel-media-sdk # TIGER LAKE(2020+) libva-intel-driver vpl-gpu-rt

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing packages"

	package_installer "mesa vulkan-intel"
}

qemu_gpu() {
	gpu_kernel_parameters=""

	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing packages"

	package_installer "qemu-guest-agent vulkan-virtio lib32-vulkan-virtio"
}

setup_laptop() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing laptop-detect package"

	package_installer "laptop-detect"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Checking if device is laptop"

	laptop-detect
	laptop_status=$?

	if [ $laptop_status = 0 ]; then
		echo -e "-------------------------------------------------------------------------"
		echo -e "Installing laptop packages"

		package_installer "auto-cpufreq switcheroo-control"

		systemctl mask power-profiles-daemon.service
		systemctl enable auto-cpufreq.service

		systemctl enable switcheroo-control.service

	elif [ $laptop_status = 1 ]; then
		echo -e "-------------------------------------------------------------------------"
		echo -e "Device not recognized as laptop"

	elif [ $laptop_status = 2 ]; then
		laptop-detect -v
	fi

	echo -e "-------------------------------------------------------------------------"
	echo -e "Uninstalling laptop-detect package"

	pacman -Rs --noconfirm laptop-detect
}

setup_hibernation() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting swapfile offset for hibernation kernel parameter"

	swap_uuid=$(findmnt -no UUID -T /swap/swapfile)
	swapfile_offset=$(btrfs inspect-internal map-swapfile -r /swap/swapfile)

	sed -i "s/\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 resume_offset=$swapfile_offset resume=UUID=$swap_uuid\"/" /etc/default/grub

	if [[ $disk_encryption != "yes" ]]; then
		echo -e "-------------------------------------------------------------------------"
		echo -e "Adding 'resume' hook for hibernation"

		sed -i '/^HOOKS=(/ s/)/ resume)/' /etc/mkinitcpio.conf
	fi
}

install_packages() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing system packages"

	[[ $install_type == "lite" ]] && package_installer "/Archer-main/quiver/lite_packages.txt"
	[[ $install_type == "kde" ]] && package_installer "/Archer-main/quiver/kde_packages.txt"
}

setup_environment() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting up desktop environment"

	[[ $install_type == "lite" ]]
	[[ $install_type == "kde" ]] && source "/Archer-main/quiver/kde_setup"
}

bash_config() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Configuring /etc/bash.bashrc"

	cat /Archer-main/quiver/bashrc/bash.bashrc >>/etc/bash.bashrc

	echo -e "-------------------------------------------------------------------------"
	echo -e "Configuring /etc/bash.bash_aliases"

	cat /Archer-main/quiver/bashrc/bash.bash_aliases >/etc/bash.bash_aliases

	echo -e "-------------------------------------------------------------------------"
	echo -e "Configuring /home/$user/.bashrc"

	sed -i '/PS1/d' /home/"$user"/.bashrc
	sed -i '/alias/d' /home/"$user"/.bashrc

	cat /Archer-main/quiver/bashrc/user.bashrc >>/home/"$user"/.bashrc
	chown "$user":"$user" /home/"$user"/.bashrc

	echo -e "-------------------------------------------------------------------------"
	echo -e "Linking /home/$user/.bashrc to /root/.bashrc"

	ln -s /home/"$user"/.bashrc /root/.bashrc

	echo -e "-------------------------------------------------------------------------"
	echo -e "Configuring /home/$user/.bash_aliases"

	cat /Archer-main/quiver/bashrc/user.bash_aliases >>/home/"$user"/.bash_aliases
	chown "$user":"$user" /home/"$user"/.bash_aliases
}

yabsnap_setup() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Installing Yabsnap"

	package_installer "yabsnap"

	echo -e "-------------------------------------------------------------------------"
	echo -e "Creating Yabsnap root config"

	yabsnap create-config root

	sed -i 's/source =/source = \//' /etc/yabsnap/configs/root.conf
	sed -i 's/keep_user = 1/keep_user = 2/' /etc/yabsnap/configs/root.conf
	sed -i 's/trigger_interval = 1 hour/trigger_interval = 5 minutes/' /etc/yabsnap/configs/root.conf
	sed -i 's/keep_preinstall = 1/keep_preinstall = 10/' /etc/yabsnap/configs/root.conf
	sed -i 's/keep_daily = 0/keep_daily = 7/' /etc/yabsnap/configs/root.conf

	echo -e "-------------------------------------------------------------------------"
	echo -e "Excluding /.snapshots from updatedb"

	echo "PRUNENAMES = \".snapshots\"" >>/etc/updatedb.conf

	echo -e "-------------------------------------------------------------------------"
	echo -e "Enabling Yabsnap service"

	systemctl enable yabsnap.timer

	echo -e "-------------------------------------------------------------------------"
	echo -e "Changing grub-btrfs title format"
	sed -i 's|^#\?GRUB_BTRFS_TITLE_FORMAT=.*|GRUB_BTRFS_TITLE_FORMAT=("snapshot" "description")|' /etc/default/grub-btrfs/config
}

snapshot_rollback() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting up Snapshot rollback script"

	cat /Archer-main/quiver/scripts/rollback >/usr/local/bin/rollback
	chmod a+x /usr/local/bin/rollback

	cat /Archer-main/quiver/scripts/rollback-tui >/usr/local/bin/rollback-tui
	chmod a+x /usr/local/bin/rollback-tui
}

package_config() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Configuring installed packages"

	installed_packages=$(pacman -Q)

	while IFS= read -r line; do

		package_name=$(echo "$line" | awk '{print $1}')

		if [[ -f "/Archer-main/quiver/package-config/$package_name" ]]; then
			echo -e "-------------------------------------------------------------------------"
			echo "Found $package_name config"

			source "/Archer-main/quiver/package-config/$package_name"

            if declare -f boot_config >/dev/null; then
                {
                    echo "Creating boot config for $package_name"
                    declare -f boot_config | sed '1,2d;$d'

                } >> /usr/local/bin/archer-boot
                unset -f boot_config
            fi
		fi
	done <<<"$installed_packages"

	if [ "$install_type" != "lite" ]; then
		echo -e "-------------------------------------------------------------------------"
		echo -e "Configuring not installed packages"

		find "/Archer-main/quiver/package-config/" -type f -name '_*' | while IFS= read -r config_path; do source "$config_path"; done
	fi

	echo -e "-------------------------------------------------------------------------"
	echo -e "Moving pacman hooks"

	mv /Archer-main/quiver/hooks/* /etc/pacman.d/hooks/
	chown -R :wheel /etc/pacman.d/hooks/*

	echo -e "-------------------------------------------------------------------------"
	echo -e "Rebuilding GRUB configs"

	grub-mkconfig -o /boot/grub/grub.cfg

	echo -e "-------------------------------------------------------------------------"
	echo -e "Making sure /home/$user belongs to $user"
	chown -R "$user":"$user" /home/"$user"
}

boot_script() {
	if [ "$prepared" != "yes" ]; then
	    echo -e "-------------------------------------------------------------------------"
		echo -e "Preparing boot script"

        cat <<-END >/usr/bin/archer-boot
#!/bin/bash
echo -e "
-------------------------------------------------------------------------
\$(tput setaf 4)
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
\$(tput sgr0)
-------------------------------------------------------------------------
                           Arch install script"
END
        prepared="yes"

	else
        cat <<-END >>/usr/bin/archer-boot
echo -e "-------------------------------------------------------------------------"
echo -e "Cleaning up script"

systemctl disable --now archer-boot.service
rm -f /etc/systemd/system/archer-boot.service
rm -f \${BASH_SOURCE[0]}
exit
END
    fi
	chmod a+x /usr/bin/archer-boot

	cat <<-END >/etc/systemd/system/archer-boot.service
[Unit]
Description=Archer boot setup script

[Service]
ExecStart=/usr/bin/archer-boot

[Install]
WantedBy=multi-user.target
END

	systemctl enable archer-boot.service
}

exit_chroot() {
	echo "-------------------------------------------------------------------------"
	echo "Restoring password requirement for wheel group"

	sed -i 's/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
	exit
}

sudo_quiet() { grep -v "unable to find terminal name for device"; }

package_installer() {
	input_packages=$1
	package_manager=$2
	max_tries=3
	try_count=0

	if [[ "$input_packages" == *.txt ]]; then
		packages=$(grep -v '^#' "$input_packages" | grep -v '^$' | grep -v '\.')
	else
		packages=$input_packages
	fi

	while [ "$try_count" -lt "$max_tries" ]; do
		try_count=$((try_count + 1))

		# shellcheck disable=SC2086
		if [ "$package_manager" == "pacman" ]; then
			pacman -S --needed --noconfirm $packages && break

		else
			sudo -u "$user" paru -S --needed --noconfirm $packages 2>&1 | sudo_quiet && break
		fi

		echo "$(tput setaf 9)Package installation failed. Retrying... ($try_count/$max_tries)$(tput sgr0)"
	done

	if [ "$try_count" == "$max_tries" ]; then
		echo "$(tput setaf 9)Package installation failed after $try_count attempts$(tput sgr0)"

		echo -e "Choose option"
		echo -e "1. Try again"
		echo -e "2. Exit"

		while true; do
			read -r -p "Select: " choice

			case $choice in
			[yY1])
				try_count=0
				package_installer "$packages" "$package_manager"
				break
				;;
			[nN2])
				echo "$(tput setaf 9)Exiting...$(tput sgr0)"
				exit
				;;
			esac
		done
	fi
}

setup_pacman
setup_system
setup_paru_pipx
setup_grub
setup_cpu
setup_gpu
setup_laptop
setup_hibernation

install_packages
yabsnap_setup
snapshot_rollback
setup_environment
bash_config
boot_script
package_config
boot_script
exit_chroot
