#!/bin/bash

sudo echo >/dev/null
# Patch 1
cat <<-END > $HOME/user-dirs.defaults
# Default settings for user directories
#
# The values are relative pathnames from the home directory and
# will be translated on a per-path-element basis into the users locale
DESKTOP=Desktop
DOWNLOAD=Downloads
TEMPLATES=Templates
PUBLICSHARE=Public
DOCUMENTS=Documents
MUSIC=Music
PICTURES=Pictures
VIDEOS=Videos
PROJECTS=Projects
# Another alternative is:
#MUSIC=Documents/Music
#PICTURES=Documents/Pictures
#VIDEOS=Documents/Videos
APPLICATIONS=Applications
GAMES=Games
END
sudo mv $HOME/user-dirs.defaults /etc/xdg/user-dirs.defaults

{
echo "[Desktop Entry]"
echo "Icon=folder-publicshare"
} >> /home/"$USER"/Public/.directory

rm /home/"$USER"/Applications/.directory
{
echo "[Desktop Entry]"
echo "Icon=folder-appimage"
} >> /home/"$USER"/Applications/.directory

rm -rf $HOME/Share

xdg-user-dirs-update --force

# Patch 2
sudo sed -i '$d' /etc/updatedb.conf
sudo sed -i 's/^PRUNENAMES = "\(.*\)"/PRUNENAMES = "\1 .snapshots"/' /etc/updatedb.conf

sudo updatedb

# Patch 3

rm "$HOME"/.local/share/user-places.xbel