#!/bin/bash
# shellcheck disable=SC2034
gpu_kernel_parameters=""

echo -e "-------------------------------------------------------------------------"
echo -e "Installing packages"

package_installer "mesa vulkan-radeon xf86-video-amdgpu"
