# archer-backup configuration file
# Any array named _INCLUDE will be checked
# Paths can be both files and directories

NAME="Archer"

# Common paths
CONFIG_DIR="$HOME/.config"
BIN_DIR="$HOME/.local/bin"
SHARE_DIR="$HOME/.local/share"

HOME_INCLUDE=(
    "$HOME/.fonts"
    "$HOME/.icons"
    "$HOME/.themes"
)

SHARE_INCLUDE=(
    "$SHARE_DIR/aurorae"
    "$SHARE_DIR/color-schemes"
    "$SHARE_DIR/fonts"
    "$SHARE_DIR/icons"
    "$SHARE_DIR/konsole"
    "$SHARE_DIR/kwin"
    "$SHARE_DIR/plasma"
    "$SHARE_DIR/wallpapers"
)

CONFIG_INCLUDE=(
    "$CONFIG_DIR/Kvantum"
    "$CONFIG_DIR/breezerc"
    "$CONFIG_DIR/dolphinrc"
    "$CONFIG_DIR/gtk-2.0"
    "$CONFIG_DIR/gtk-3.0"
    "$CONFIG_DIR/gtk-4.0"
    "$CONFIG_DIR/gtkrc"
    "$CONFIG_DIR/gtkrc-2.0"
    "$CONFIG_DIR/kate"
    "$CONFIG_DIR/katerc"
    "$CONFIG_DIR/kcminputrc"
    "$CONFIG_DIR/kdeglobals"
    "$CONFIG_DIR/kglobalshortcutsrc"
    "$CONFIG_DIR/khotkeysrc"
    "$CONFIG_DIR/klipperrc"
    "$CONFIG_DIR/konsolerc"
    "$CONFIG_DIR/krunnerrc"
    "$CONFIG_DIR/kscreenlockerrc"
    "$CONFIG_DIR/ksmserverrc"
    "$CONFIG_DIR/ksplashrc"
    "$CONFIG_DIR/kwinrc"
    "$CONFIG_DIR/kwinrulesrc"
    "$CONFIG_DIR/latte"
    "$CONFIG_DIR/lattedockrc"
    "$CONFIG_DIR/lightlyrc"
    "$CONFIG_DIR/oxygenrc"
    "$CONFIG_DIR/plasma-org.kde.plasma.desktop-appletsrc"
    "$CONFIG_DIR/plasmarc"
    "$CONFIG_DIR/plasmashellrc"
)

# Code OSS settings
#CODE_OSS_INCLUDE=("$CONFIG_DIR/Code - OSS/User/settings.json")

# Firefox customization
#FIREFOX_INCLUDE=("$HOME/.mozilla/firefox/*.default-release/chrome")
