#!/bin/bash
# Archer config file

echo -e "-------------------------------------------------------------------------"
echo -e "Setting Discord to use local login credentials"

sed -i 's/Exec=\/usr\/bin\/discord/Exec=\/usr\/bin\/discord --password-store=basic/' /opt/discord/discord.desktop

echo -e "-------------------------------------------------------------------------"
echo -e "Removing Discord internal update check"

sudo -u "$user" mkdir -p /home/"$user"/.config/discord
sudo -u "$user" touch /home/"$user"/.config/discord/settings.json

cat <<-END > /home/"$user"/.config/discord/settings.json
{
  "IS_MAXIMIZED": false,
  "IS_MINIMIZED": false,
  "SKIP_HOST_UPDATE": true,
  "WINDOW_BOUNDS": {
    "x": 40,
    "y": 40,
    "width": 940,
    "height": 570
  }
}
END