#!/bin/bash
# Archer config file

echo -e "Configuring fastfetch"
sudo -u "$user" mkdir -p /home/"$user"/.config/fastfetch/

cat /Archer-main/quiver/configs/fastfetch-config.jsonc > /home/"$user"/.config/fastfetch/config.jsonc
cat /Archer-main/quiver/configs/fastfetch-config-small.jsonc > /home/"$user"/.config/fastfetch/config-small.jsonc

chown "$user":"$user" /home/"$user"/.config/fastfetch/config.jsonc
chown "$user":"$user" /home/"$user"/.config/fastfetch/config-small.jsonc

mkdir -p /home/root/.config/fastfetch/

cat /Archer-main/quiver/configs/fastfetch-config.jsonc > /root/.config/fastfetch/config.jsonc
cat /Archer-main/quiver/configs/fastfetch-config-small.jsonc > /root/.config/fastfetch/config-small.jsonc

chown root:root /home/root/.config/fastfetch/config.jsonc
chown root:root /home/root/.config/fastfetch/config-small.jsonc