#!/bin/bash
# Archer config file

echo -e "-------------------------------------------------------------------------"
echo -e "Configuring fastfetch"

sudo -u "$user" mkdir -p /home/"$user"/.config/fastfetch/
cat /Archer-main/quiver/configs/fastfetch-config.jsonc > /home/"$user"/.config/fastfetch/config.jsonc
cat /Archer-main/quiver/configs/fastfetch-config-small.jsonc > /home/"$user"/.config/fastfetch/config-small.jsonc

chown "$user":"$user" /home/"$user"/.config/fastfetch/config.jsonc
chown "$user":"$user" /home/"$user"/.config/fastfetch/config-small.jsonc