#!/bin/bash
# Archer config file

echo -e "-------------------------------------------------------------------------"
echo -e "Enabling networkmanager service"

systemctl enable NetworkManager.service