#!/bin/bash
# Archer config file
# This is for configuration of all the packages that did not get installed

if ! pacman -Q steam > /dev/null; then
    echo -e "-------------------------------------------------------------------------"
    echo -e "Installing steam-devices package for Steam Flatpak"
	
    package_installer "steam-devices" 
fi

if ! pacman -Q firefox > /dev/null; then
    echo -e "-------------------------------------------------------------------------"
    echo -e "Preparing Betterfox user.js for flatpak version"

    mv /Archer-main/quiver/config/betterfox-userjs /home/"$user"/.user.js
	chown "$user":"$user" /home/"$user"/.user.js
fi