#!/bin/bash
# shellcheck disable=SC2154
echo -e "-------------------------------------------------------------------------"
echo -e "Installing archer-backup"

mv /Archer-main/quiver/scripts/archer-backup /usr/local/bin/archer-backup
chmod a+x /usr/local/bin/archer-backup

sudo -u "$user" /usr/local/bin/archer-backup --restore /Archer-main/quiver/configs/Archer.tar.gz
rm /home/$user/archer-backup
rm /home/$user/archer-backup.conf

echo -e "-------------------------------------------------------------------------"
echo -e "Setting SDDM theme"

mkdir -p /etc/sddm.conf.d/
cat <<-END >/etc/sddm.conf.d/kde_settings.conf
[Theme]
Current=breeze
END
