#!/bin/bash
# Archer config file

echo -e "Enabling automatic D-Bus activation for KWallet"
cat <<-END >> /usr/share/dbus-1/services/org.freedesktop.secrets.service
[D-BUS Service]
Name=org.freedesktop.secrets
Exec=/usr/bin/kwalletd6
END