#!/usr/bin/env bash
user="UNIX_USER"

echo -ne "
-------------------------------------------------------------------------
$(tput setaf 4)
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
$(tput sgr0)
-------------------------------------------------------------------------
		                   Plasma setup script
-------------------------------------------------------------------------"
echo -e "Importing and applying konsave settings"

export PATH=\$PATH:/home/$user/.local/bin

sudo -u $user konsave -i /home/$user/archer.knsv
sleep 1
sudo -u $user konsave -a archer


#echo -e "-------------------------------------------------------------------------"
#echo -e "Setting Dolphin state"

#sudo -u $user mkdir -p /home/$user/.local/share/dolphin
#sudo -u $user touch /home/$user/.local/share/dolphin/dolphinstaterc

#cat <<-EOF > /home/$user/.local/share/dolphin/dolphinstaterc
#[State]
#State=AAAA/wAAAAD9AAAAAwAAAAAAAACmAAAB0/wCAAAAAvsAAAAWAGYAbwBsAGQAZQByAHMARABvAGMAawAAAAAuAAAA7AAAAAoBAAAD+wAAABQAcABsAGEAYwBlAHMARABvAGMAawEAAAAuAAAB0wAAAF0BAAADAAAAAQAAALgAAAHn/AIAAAAB+wAAABAAaQBuAGYAbwBEAG8AYwBrAAAAAC4AAAHnAAAACgEAAAMAAAADAAAC+AAAAL78AQAAAAH7AAAAGAB0AGUAcgBtAGkAbgBhAGwARABvAGMAawAAAAAAAAAC+AAAAAoBAAADAAACkwAAAdMAAAAEAAAABAAAAAgAAAAI/AAAAAEAAAACAAAAAQAAABYAbQBhAGkAbgBUAG8AbwBsAEIAYQByAQAAAAD/////AAAAAAAAAAA=
#EOF

rm -f /home/$user/archer.knsv
rm -f ${BASH_SOURCE[0]}