#!/usr/bin/env bash
user="UNIX_USER"

echo -e "
-------------------------------------------------------------------------
$(tput setaf 4)
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
$(tput sgr0)
-------------------------------------------------------------------------
		                   Plasma setup script
-------------------------------------------------------------------------"
echo -e "Importing and applying konsave settings"

export PATH=$PATH:/home/$user/.local/bin

sudo -u $user konsave -i /home/$user/archer.knsv
sleep 1
sudo -u $user konsave -a archer

rm -f /home/$user/archer.knsv
rm -f ${BASH_SOURCE[0]}