#!/usr/bin/env bash
echo -ne "#ARCHER_LOGO#"
echo -e "
                        Snapshot rollback script
-------------------------------------------------------------------------"

sudo echo "" > /dev/null

root_disk=$(cat /proc/cmdline | awk '{sub("root=UUID=", "", $2); print $2}')
snaphot_number=$(cat /proc/cmdline | awk -F '/' '{print $3}')

echo -e "Mounting root on /mnt"

sudo mount "/dev/disk/by-uuid/$root_disk" /mnt

echo -e "-------------------------------------------------------------------------"
echo -e "Moving broken root"

sudo mv /mnt/@ /mnt/@broken

echo -e "-------------------------------------------------------------------------"
echo -e "Setting snapshot as root"

sudo btrfs subvolume snapshot /mnt/@snapshots/#SNAPSHOT_PATH# /mnt/@ && success="yes"

echo -e "-------------------------------------------------------------------------"
echo -e "Removing broken root"

[[ $success == "yes" ]] && sudo rm -rf /mnt/@broken

if [ -e "/mnt/@/var/lib/pacman/db.lck" ]; then

	echo -e "-------------------------------------------------------------------------"
	echo -e "Removing pacman db.lck"

	sudo rm /mnt/@/var/lib/pacman/db.lck
fi

echo -e "-------------------------------------------------------------------------"
echo -e "Unmounting /mnt"

sudo umount -R /mnt

read -p "Press any key to reboot..."
reboot