#!/bin/bash
# shellcheck disable=SC2034
gpu_kernel_parameters=""

# Untested
# Optional dependencies for libva
# intel-media-driver: backend for Intel GPUs (>= Broadwell)
# libva-intel-driver: backend for Intel GPUs (<= Haswell)

echo -e "-------------------------------------------------------------------------"
echo -e "Installing packages"

package_installer "mesa vulkan-intel"
