# Use human readable units. Can be y/n or 1/0.
human_readable=y

# Set the output verbosity. Can be "quiet" | "normal" | "verbose".
verbosity=quiet

# Use an hashfile as cache. This lowerers memory usage for higher overhead.
# Can be y/n or 1/0.
hashfile=y

# The hash block size. Specify a custom value in kilobytes, otherwise set
# "default" for the default value. Lower values increase deduplication
# opportunities and memory usage.
size=default

# The base paths to start deduplicating. Split by spaces.
include_paths=(/)

# Paths to exclude from deduplication. Split by spaces.
exclude_paths=(/root /home /var/log /var/lib/flatpak /var/lib/libvirt /var/tmp /var/cache /var/spool /srv)
