#!/usr/bin/env bash
show_logo() {
	clear
	archer_logo="
-------------------------------------------------------------------------
$(tput setaf 4)
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
$(tput sgr0)
-------------------------------------------------------------------------"
	echo -ne "$archer_logo"
	echo -e "
                          Archer rescue script
-------------------------------------------------------------------------"
}

set_root() {
	local status=1
	while [ $status -ne 0 ]; do
		echo -e "Listing available disks"

		lsblk

		echo -e "Enter ROOT partition"
		read -r -p "Disk: " root_partition

		echo "p" | fdisk "$root_partition"
		status=$?
	done

	while true; do
		read -r -p "Is root partition $root_partition correct? (Y/n) " yn

		case $yn in
		[yY1]) break ;;
		[nN2])
			set_root
			break ;;
		esac
	done
}

set_boot() {
	local status=1
	while [ $status -ne 0 ]; do
		echo -e "-------------------------------------------------------------------------"
		echo -e "Listing available disks"

		lsblk

		echo -e "Enter BOOT partition"
		read -r -p "Disk: " efi_partition

		echo "p" | fdisk "$efi_partition"
		status=$?
	done

	while true; do
		read -r -p "Is the boot partition $efi_partition correct? (Y/n) " yn

		case $yn in
		[yY1]) break ;;
		[nN2])
			set_boot
			break ;;
		esac
	done
}

umount_system() {
	echo -e "-------------------------------------------------------------------------"
	echo -e "Unounting btrfs subvolumes"

	umount /mnt/boot
	umount -t btrfs /mnt/root
	umount -t btrfs /mnt/home
	umount -t btrfs /mnt/var/log
	umount -t btrfs /mnt/var/cache/pacman/pkg
	umount -t btrfs /mnt/var/tmp
	umount -t btrfs /mnt/var/cache
	umount -t btrfs /mnt/var/spool
	umount -t btrfs /mnt/srv
	umount -t btrfs /mnt

}

show_logo
umount_system
archer_chroot
