#!/bin/bash
# shellcheck disable=SC2002,SC2164,SC2086
user="UNIX_USER"
packages="PACKAGE_LIST"

show_logo() {
	clear
	echo -e "
-------------------------------------------------------------------------
$(tput setaf 4)
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
$(tput sgr0)
-------------------------------------------------------------------------
                         Flatpak install script
-------------------------------------------------------------------------"
}

install_flatpak() {
	while ! ping -q -c 1 -W 1 archlinux.org > /dev/null 2>&1; do
    	echo "Waiting for internet connection..."
		sleep 10
	done

    while true; do
		flatpak install flathub -y --noninteractive $packages && break
    	echo "$(tput setaf 9)Package installation failed. Retrying...$(tput sgr0)"
	done


    echo -e "Fix game controller remote access pop up spam in KDE Plasma"
    flatpak permission-set kde-authorized remote-desktop "" yes

	# Setup flatpaks
	if [[ $(flatpak list) == *"com.flatpak.package.name"* ]]; then
        # Example code to configure flatpaks
        echo
	fi

	echo -e "-------------------------------------------------------------------------"
	read -r -t 5 -p "Rebooting in 5 seconds..."

	rm -f /home/$user/.config/autostart/flatpak-setup.desktop
	rm -f ${BASH_SOURCE[0]}
	reboot
}

show_logo
install_flatpak
