#!/bin/bash
# shellcheck disable=SC2002,SC2162,SC2086
hostname="HOSTNAME"

echo -e "
-------------------------------------------------------------------------
$(tput setaf 4)
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
$(tput sgr0)
-------------------------------------------------------------------------
                        Snapshot rollback script
-------------------------------------------------------------------------"

root_uuid=$(lsblk -o UUID,LABEL | grep "$hostname" | awk '{print $1}')
snapshot_path=$(cat /proc/cmdline | grep -oP '(?<=subvol=)[^ ]*')

sudo echo -e "Mounting root on /mnt"

sudo mount "/dev/disk/by-uuid/$root_uuid" /mnt

echo -e "-------------------------------------------------------------------------"
echo -e "Moving broken root"

sudo mv /mnt/@ /mnt/@broken

echo -e "-------------------------------------------------------------------------"
echo -e "Setting current snapshot as new root"

#sudo btrfs subvolume snapshot / /mnt/@ && success="yes"
#GRUB sudo btrfs subvolume snapshot /mnt/$snapshot_path
sudo btrfs subvolume snapshot /$snapshot_path /mnt/@ && success="yes"

echo -e "-------------------------------------------------------------------------"
echo -e "Removing broken root"

[[ $success == "yes" ]] && sudo rm -rf /mnt/@broken && echo "Removed"

if [ -e "/mnt/@/var/lib/pacman/db.lck" ]; then

	echo -e "-------------------------------------------------------------------------"
	echo -e "Removing pacman db.lck"

	sudo rm /mnt/@/var/lib/pacman/db.lck
fi

echo -e "-------------------------------------------------------------------------"
echo -e "Unmounting /mnt"

sudo umount -R /mnt

read -p "Press any key to reboot..."
reboot