#!/bin/bash
# shellcheck disable=SC2086
show_logo() {
	clear
	echo -e "
-------------------------------------------------------------------------
\e[34m
             █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
            ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
            ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
            ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
            ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
            ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
\e[0m
-------------------------------------------------------------------------
                            Wine setup script
-------------------------------------------------------------------------"
}

menu() {
	echo -e "1. Setup Wine"
	echo -e "2. Exit"
	echo -e "0. Remove script"
	while true; do
		read -r -p "Select:  " selection

		case $selection in
		[0])
			remove_script
			break ;;
		[1])
			install_wine
			break ;;
		[2])
			exit
		esac
	done
}

install_wine() {
	echo -e "Installing Wine packages"

	sudo pacman -S wine wine-gecko wine-mono winetricks

	echo -e "-------------------------------------------------------------------------"
	echo -e "Setting Wine to Win10"

	winetricks win10

	echo -e "Installing Wine libraries and frameworks"

	winetricks -q d3dx10 d3dx9 dotnet35 dotnet40 dotnet45 dotnet48 dxvk vcrun2008 vcrun2010 vcrun2012 vcrun2019 vcrun6sp6

	echo -e "-------------------------------------------------------------------------"
	echo -e "Checking installed Wine libraries and frameworks"

	winetricks -q d3dx10 d3dx9 dotnet35 dotnet40 dotnet45 dotnet48 dxvk vcrun2008 vcrun2010 vcrun2012 vcrun2019 vcrun6sp6

	echo -e "-------------------------------------------------------------------------"
	read -r -p "Press any key to continiue..."

	show_logo
	menu
}

remove_script() {
	rm -f /home/$USER/.config/autostart/wine-setup.desktop
	rm -f ${BASH_SOURCE[0]}
}

show_logo
menu
