#!/bin/bash
# Archer config file
# This file is for extra package configuration
# Use the boot_config function in any 'Archer config file' to write code to the
# archer-boot script which then will be ran first time booting in to the new system

# shellcheck disable=SC2154
if [ "$install_type" != "lite" ] && ! pacman -Q steam >/dev/null 2>&1; then
    # If steam was not installed then prepare with steam-devices package
    echo "Installing steam-devices package for Steam Flatpak"
    package_installer "steam-devices"
fi

boot_config() {
    keyboard_keymap=$(awk -F= '/^KEYMAP=/{print $2}' /etc/vconsole.conf)
    default_locale=$(awk -F= '/^LANG=/{print $2}' /etc/locale.conf)

    echo -e "Setting keymap ($keyboard_keymap) and locale ($default_locale) system-wide"
    # shellcheck disable=SC2086
    localectl set-keymap $keyboard_keymap
    # shellcheck disable=SC2086
    localectl set-locale $default_locale
}

echo -e "-------------------------------------------------------------------------"
echo -e "Creating Archer-Config desktop entry"

cat <<-END > /usr/share/applications/archer-config.desktop
[Desktop Entry]
Type=Application
Name=Archer Configuration Toolkit
Comment=Install and configure new features
Exec=konsole -e bash <(curl -fsSL https://raw.githubusercontent.com/Martan404/Archer-Config/main/archer-config) --temp
Terminal=false
Icon=project-open
Categories=Utility;
END
