#!/bin/bash
# Archer config file
# This file is for extra package configuration
# Use the boot_config function in any 'Archer config file' to write code to the
# archer-boot script which then will be ran first time booting in to the new system

# shellcheck disable=SC2154
if [ "$install_type" != "lite" ] && ! pacman -Q steam >/dev/null 2>&1; then
    # If steam was not installed then prepare with steam-devices package
    echo "Installing steam-devices package for Steam Flatpak"
    package_installer "steam-devices"
fi

boot_config() {
    keyboard_keymap=$(awk -F= '/^KEYMAP=/{print $2}' /etc/vconsole.conf)
    default_locale=$(awk -F= '/^LANG=/{print $2}' /etc/locale.conf)

    echo -e "Setting keymap ($keyboard_keymap) and locale ($default_locale) system-wide"
    # shellcheck disable=SC2086
    localectl set-keymap $keyboard_keymap
    # shellcheck disable=SC2086
    localectl set-locale $default_locale
}

echo -e "-------------------------------------------------------------------------"
echo -e "Setting up Archer-Config"

mkdir -p /home/"$user"/.config/autostart/
chown "$user":"$user" /home/"$user"/.config/autostart/
chmod 755 /home/"$user"/.config/autostart/

cat <<-END > /home/"$user"/.config/autostart/Archer-Config.desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=Archer Configuration Toolkit
Comment=Launch Archer Configuration Toolkit
Exec=konsole -e bash <(curl -fsSL https://raw.githubusercontent.com/Martan404/Archer-Config/main/archer-config) --temp; rm -f ~/.config/autostart/Archer-Config.desktop
Terminal=false
Icon=breeze-settings
Categories=Utility;
END
chown "$user":"$user" /home/"$user"/.config/autostart/Archer-Config.desktop