#!/bin/bash
# shellcheck disable=SC2154,SC2002,SC2164,SC2086

echo -e "Creating flatpak-installer desktop entry"

mkdir -p /home/"$user"/.config/autostart/
chown "$user":"$user" /home/"$user"/.config/autostart/
chmod 755 /home/"$user"/.config/autostart/

cat <<END >>/home/"$user"/.config/autostart/flatpak-installer.desktop
[Desktop Entry]
Exec=konsole -e /home/"$user"/.local/bin/flatpak-installer
Icon=/usr/share/pixmaps/archlinux-logo.png
StartupNotify=true
Type=Application
END
chown "$user":"$user" /home/"$user"/.config/autostart/flatpak-installer.desktop

echo -e "Setting up Flatpak install script"

flatpak_install_script() {
    #!/bin/bash
    user="UNIX_USER"
    packages="PACKAGE_LIST"

    clear
    echo -e "
    -------------------------------------------------------------------------
    $(tput setaf 4)
                 █████╗ ██████╗  ██████╗██╗  ██╗███████╗██████╗
                ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔════╝██╔══██╗
                ███████║██████╔╝██║     ███████║█████╗  ██████╔╝
                ██╔══██║██╔══██╗██║     ██╔══██║██╔══╝  ██╔══██╗
                ██║  ██║██║  ██║╚██████╗██║  ██║███████╗██║  ██║
                ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
    $(tput sgr0)
    -------------------------------------------------------------------------
                            Flatpak install script
    -------------------------------------------------------------------------"

    while ! ping -q -c 1 -W 1 archlinux.org > /dev/null 2>&1; do
        echo "Waiting for internet connection..."
        sleep 10
    done

    while true; do
        flatpak install flathub --system --assumeyes --noninteractive $packages && break
        echo "$(tput setaf 9)Package installation failed. Retrying...$(tput sgr0)"
        sleep 3
    done

    echo -e "Fix game controller remote access pop up spam in KDE Plasma"
    flatpak permission-set kde-authorized remote-desktop "" yes

    # Setup flatpaks
    if [[ $(flatpak list) == *"com.flatpak.package.name"* ]]; then
        # Example code to configure flatpaks
        echo
    fi

    echo -e "-------------------------------------------------------------------------"
    read -r -t 5 -p "Rebooting in 5 seconds..."

    rm -f /home/$user/.config/autostart/flatpak-installer.desktop
    rm -f ${BASH_SOURCE[0]}
    reboot
}

mkdir -p /home/"$user"/.local/bin/

echo "#!/bin/bash" > /home/"$user"/.local/bin/flatpak-installer
declare -f flatpak_install_script | tail -n +3 | head -n -1 | sed 's/^[[:space:]]\{4\}//' >> /home/"$user"/.local/bin/flatpak-installer

chmod a+x /home/"$user"/.local/bin/flatpak-installer
chown "$user":"$user" /home/"$user"/.local/bin/flatpak-installer

packages=$(sed -n '/# FLATPAK/{:a;n;/# FLATPAK/b;p;ba}' "/Archer-main/quiver/${install_type}_packages.txt" | tr '\n' ' ')
sed -i "s/UNIX_USER/$user/g; s/PACKAGE_LIST/$packages/g" /home/"$user"/.local/bin/flatpak-installer
