#!/bin/bash
# Archer config file
# This is for configuring packages that did not get installed

echo -e "Enabling Grub OS prober"

sed -i '/^[#]*GRUB_DISABLE_OS_PROBER=/s/true/false/' /etc/default/grub
sed -i '/^#GRUB_DISABLE_OS_PROBER/s/^#//' /etc/default/grub