#!/bin/bash
# Archer config file

echo -e "Setting up XDG user directories"
xdg-user-dirs-update

#sed -i '/TEMPLATES/s/^/#/' /etc/xdg/user-dirs.defaults
sed -i '/PUBLICSHARE/s/^/#/' /etc/xdg/user-dirs.defaults

cat <<-END >> /etc/xdg/user-dirs.defaults
APPLICATIONS=Applications
GAMES=Games
PROJECTS=Projects
SYNC=Sync
END

echo -e "Creating home sub-directories for $user"
sudo -u "$user" xdg-user-dirs-update --force

echo -e "Creating home/System sub-directories for $user"
sudo -u "$user" mkdir -p /home/"$user"/System/{icons,scripts}


echo -e "Setting sub-directory icons"
sudo -u "$user" touch /home/"$user"/{Applications,Games,Projects,Sync,System}/.directory
{
echo "[Desktop Entry]"
echo "Icon=folder-flatpak"
} >> /home/"$user"/Applications/.directory
{
echo "[Desktop Entry]"
echo "Icon=folder-games"
} >> /home/"$user"/Games/.directory
{
echo "[Desktop Entry]"
echo "Icon=folder-script"
} >> /home/"$user"/Projects/.directory
{
echo "[Desktop Entry]"
echo "Icon=folder-cloud"
} >> /home/"$user"/Sync/.directory
{
echo "[Desktop Entry]"
echo "Icon=folder-build" 
} >> /home/"$user"/System/.directory