#!/bin/bash
# shellcheck disable=SC2034
cpu_kernel_parameters="nowatchdog modprobe.blacklist=sp5100_tco"

echo -e "-------------------------------------------------------------------------"
echo -e "Installing packages"

package_installer "amd-ucode"
